/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_roomchannel_free: (a: number, b: number) => void;
export const __wbg_roomsender_free: (a: number, b: number) => void;
export const __wbg_summernode_free: (a: number, b: number) => void;
export const roomchannel_close: (a: number) => void;
export const roomchannel_receiver: (a: number) => any;
export const roomchannel_sender: (a: number) => number;
export const roomsender_broadcast: (a: number, b: number, c: number) => any;
export const start: () => void;
export const summernode_endpoint_id: (a: number, b: number) => void;
export const summernode_join_room: (a: number) => any;
export const summernode_spawn: () => any;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const intounderlyingsource_cancel: (a: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const ring_core_0_17_14__bn_mul_mont: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const __wasm_bindgen_func_elem_17711: (a: number, b: number, c: number, d: any) => void;
export const __wasm_bindgen_func_elem_17726: (a: number, b: number, c: any, d: any) => void;
export const __wasm_bindgen_func_elem_7641: (a: number, b: number, c: any) => void;
export const __wasm_bindgen_func_elem_4187: (a: number, b: number, c: any) => void;
export const __wasm_bindgen_func_elem_9284: (a: number, b: number, c: any) => void;
export const __wasm_bindgen_func_elem_7424: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_8560: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_8591: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_17574: (a: number, b: number) => void;
export const __wbindgen_export: (a: number, b: number) => number;
export const __wbindgen_export2: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export3: (a: number) => void;
export const __wbindgen_export4: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_export5: (a: number, b: number) => void;
export const __wbindgen_export6: (a: number, b: number, c: number) => void;
export const __wbindgen_export7: (a: number, b: number) => void;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
export const __wbindgen_export8: (a: number) => void;
export const __wbindgen_start: () => void;
