[package]
name = "summer-shared"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
iroh = { workspace = true }
iroh-gossip = { workspace = true }
n0-future = "0.3"
postcard = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
url = "2"

[build-dependencies]
cfg_aliases = "0.2"
